spring.application.name=hiriai
#Database Connection

spring.datasource.url=jdbc:mysql://localhost:3306/hiriai_db
spring.datasource.username=root
spring.datasource.password=1234@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Groq API key
groq.api.key=YOUR_GROQ_API_KEY_HERE

#Port
server.port = 8080
#HIHelloCharvieREtaerd
#hiiakdjf